SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I LEFT JOIN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE
    GROUP BY PARENT_ITEM_ID
    ) P
ON I.ITEM_ID = P.PARENT_ITEM_ID
WHERE P.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC