SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) F
ON R.FAVORITES = F.FAVORITES AND R.FOOD_TYPE = F.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC