SELECT C.YEAR, C.MONTH,
        C.USERS AS PURCHASED_USERS,
        ROUND(C.USERS / (
            SELECT COUNT(*) 
            FROM USER_INFO 
            WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM (
    SELECT YEAR(S.SALES_DATE) AS YEAR,
            MONTH(S.SALES_DATE) AS MONTH,
            COUNT(DISTINCT I.USER_ID) AS USERS
    
    FROM USER_INFO I LEFT JOIN ONLINE_SALE S
    ON I.USER_ID = S.USER_ID
    WHERE YEAR(I.JOINED) = 2021
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
) C
WHERE YEAR IS NOT NULL AND MONTH IS NOT NULL
ORDER BY C.YEAR, C.MONTH