WITH RECURSIVE HOUR 
AS (
    SELECT 9 AS H
    UNION ALL
    SELECT H + 1
    FROM HOUR
    WHERE H < 19
)
SELECT HOUR.H ,COUNT(HOUR(O.DATETIME)) AS COUNT
FROM HOUR JOIN ANIMAL_OUTS O
ON HOUR.H = HOUR(O.DATETIME)
GROUP BY HOUR.H
ORDER BY HOUR.H