SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN (
    SELECT T.ITEM_ID AS CHILD_ID
    FROM ITEM_INFO I JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
) C
ON I.ITEM_ID = C.CHILD_ID
ORDER BY I.ITEM_ID DESC