SELECT S.SCORE, S.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ) S JOIN HR_EMPLOYEES E
ON S.EMP_NO = E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;