SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN (SELECT MAX(PRICE) PRICE, CATEGORY
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) P
ON F.CATEGORY = P.CATEGORY AND F.PRICE = P.PRICE
ORDER BY MAX_PRICE DESC